const base = {
    login : '/api/user/login',
    typeUrl:'/api/common/platform',
    requestTypeUrl:'/api/common/reqeustType',
    protocolUrl:'/api/common/protocol',
    envUrl:'/api/common/env',
    projectUrl: '/api/project/',
    userUrl:'/api/user/',
    testUrl: '/api/common/testRequest',
    scriptUrl:'/api/script/',
    dubboServer:'/api/dubbo/service',
    dubboTest:'/api/dubboTest',
    historyUrl:'/api/history/',
    reportUrl:'/api/report/',
    roleUrl:"/api/common/roles",
    listRoleUrl:"/api/common/roleList",
    generateReportUrl:"/api/common/generateReport",
    logUrl:'/api/common/watchLog',
    watchReport:"/api/common/watchReport",
    report:"/html",
    execScriptUrl:'/api/common/execScript',
    findExecResult:"/api/common/findResult",
    reportDownload:'/api/common/download',
    taskUrl:"/api/scheduleJob",
    articleUrl:"/api/article",
    checkCronUrl:"/api/common/checkCron",
    imgUrl:"/api/common/upload",
    categoryurl:"/api/category",
    casLogin:"/api/case/caslogin",
    casProject:"/api/case/project",
    casModuleject:"/api/case/module",
    wsUrl : 'ws://127.0.0.1:8000/ws/deploy/tasks/'
}

export default base;